from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from huggingface_hub import HfApi
import gradio as gr
# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# --- Global Prompt Template ---
# Using the same simple template structure for the new LCEL chain
RAG_PROMPT_TEMPLATE = """You are an assistant for question-answering tasks. 
Use the following pieces of retrieved context to answer the question. 
If you don't know the answer, just say that you don't know. 
Use a concise, but comprehensive response.

Context: {context}
Question: {question}

Answer:"""
CUSTOM_RAG_PROMPT = PromptTemplate.from_template(RAG_PROMPT_TEMPLATE)

def format_docs(docs):
    """Formats a list of LangChain Document objects into a single string."""
    return "\n\n".join(doc.page_content for doc in docs)

def get_llm(): 
    model_id = 'ibm/granite-3-3-8b-instruct' 
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,
        GenParams.TEMPERATURE: 0.5
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters
        )
    return watsonx_llm

def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document

def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len
    )
    chunks = text_splitter.split_documents(data)
    return chunks 


def vector_database(chunks):
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(
        chunks,
        embedding_model)
    return vectordb 


def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 512, # oryginaly 3
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {
            "input_text": True}
        }
    watsonx_embedding = WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr-v2",
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=embed_params
        )
    return watsonx_embedding 

def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever

def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    
    # --- RAG Chain using LCEL (LangChain Expression Language) ---
    # This is the modern and preferred way to construct RAG chains in LangChain
    rag_chain = (
        {"context": retriever_obj | format_docs, "question": RunnablePassthrough()}
        | CUSTOM_RAG_PROMPT
        | llm
        | StrOutputParser() # Use output parser for a clean string result
    )
    
    # We pass the 'query' as the input to the chain, which goes to RunnablePassthrough() 
    # and is used for retrieval.
    response = rag_chain.invoke(query)
    # The result is already the string from StrOutputParser
    return response

rag_application = gr.Interface(
    fn=retriever_qa,
    inputs=[
        gr.File(label="Upload PDF File",
        file_count="single", file_types=['.pdf'],
        type="filepath"),
        gr.Textbox(label="Input Query", lines=2,
        placeholder="Type your question here...")
        ],
        outputs=gr.Textbox(label="Output"),
        title="RAG Chatbot",
        description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
    )


rag_application.launch(server_name="0.0.0.0", 
server_port= 7860)